// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcwkvlxgxvbnzfaoeipr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indjd2t2bHhneHZibnpmYW9laXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MzE0ODIsImV4cCI6MjA1NzMwNzQ4Mn0.d25s9WWNjStW7_JFKbP0cl3b4Q9XdOH--2Qpf6dhTHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);